### PR TITLE
Add Burnt as an option for Sonner to README.md

### PR DESCRIPTION
**Pull request by kevin-kidd**
## Description:
Added Burnt as an option for the Sonner section in the README.

## Tested Platforms:

- [x] Web
- [x] iOS
- [x] Android

## Affected Apps/Packages:
- README.md

### CODE REVIEW

**Comment by gunnartorfis** [comment]
Could I suggest adding Reanimated Toasts as an option? 
https://gunnartorfis.github.io/react-native-reanimated-toasts/

**Comment by mrzachnugent** [comment]
@gunnartorfis are you planning on making your implementation public and have the repo scoped on to that?

**Comment by gunnartorfis** [comment]
@mrzachnugent the repo is public, the docs are linked above. Here's the repo: https://github.com/gunnartorfis/react-native-reanimated-toasts

**Review by mrzachnugent — APPROVED** [review]
@kevin-kidd Thanks for contributing!

**Pull request merged**
