### PR TITLE
Fix Issue 34: Minor css fix popover demo

### PR DESCRIPTION
**Pull request by the-simian**
- adds `min-w-0` which fixes the overflow of textboxes inside the popover

### CODE REVIEW

**Comment by the-simian** [comment]
| Before | After|
|--------|--------|
| image| image|

**Comment by the-simian** [comment]
Device Testing: mobile devices work the same as before:
image

**Comment by the-simian** [comment]
resolves #34

**Review by mrzachnugent — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
